// No model turn: verify disabled-connection testing and a sanitized HTTP authentication failure.
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {testMcpRuntime} from '../../src/mcp/runtime.mjs';
const [root,home,exe]=process.argv.slice(2);if(!root||!home||!exe)throw Error('Supply ROOT CODEX_HOME CODEX_EXE');fs.mkdirSync(root,{recursive:true});
let calls=0;const server=http.createServer(async(req,res)=>{if(req.url.startsWith('/denied')){res.writeHead(401,{'WWW-Authenticate':'Bearer realm="synthetic"'}).end('synthetic-token-not-to-print');return;}let raw='';for await(const chunk of req)raw+=chunk;if(req.method!=='POST'){res.writeHead(405).end();return;}const m=JSON.parse(raw);if(m.method==='tools/call')calls++;if(m.id===undefined){res.writeHead(202).end();return;}let result={};if(m.method==='initialize')result={protocolVersion:m.params.protocolVersion,capabilities:{tools:{}},serverInfo:{name:'probe',version:'1'}};if(m.method==='tools/list')result={tools:[{name:'echo',inputSchema:{type:'object'}}]};res.setHeader('Content-Type','application/json');res.end(JSON.stringify({jsonrpc:'2.0',id:m.id,result}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const env={...process.env,CODEX_HOME:home};for(const k of Object.keys(env))if(/TOKEN|SECRET|PASSWORD|API_KEY/i.test(k))delete env[k];const args=['app-server','--stdio','--strict-config','-c','approval_policy="never"'];
try{const config={url:`http://127.0.0.1:${server.address().port}/ok`,enabled:false,startup_timeout_sec:5};const result=await testMcpRuntime({executable:exe,args,cwd:root,env,botId:'probe',entry:{name:'test',config}});assert.ok(result.tools.includes('echo'));assert.equal(config.enabled,false);
 await assert.rejects(testMcpRuntime({executable:exe,args,cwd:root,env,botId:'probe',entry:{name:'test',config:{url:`http://127.0.0.1:${server.address().port}/denied?token=synthetic-hidden`,startup_timeout_sec:5}}}),e=>e.code==='mcp_connection_failed'&&!e.message.includes('synthetic-hidden'));
 assert.equal(calls,0);console.log(JSON.stringify({passed:true,disabledConnectionTested:true,authenticationFailureSanitized:true,modelTurns:0,toolCalls:0}));
}finally{await new Promise(r=>server.close(r));}
