import assert from 'node:assert/strict';
import fs from 'node:fs';
import {openDatabase} from '../../src/storage/database.mjs';
import {createVault} from '../../src/storage/vault.mjs';
import {CodexAgent} from '../../src/codex/threads.mjs';
const root=process.argv[2],home=process.argv[3],exe=process.argv[4];fs.mkdirSync(root,{recursive:true});const db=openDatabase(root+'/db.sqlite');db.registerBot({botId:'vault-probe',telegramId:1,username:'test',ownerId:1});db.saveChat('vault-probe',{id:1,type:'private'});const record=db.ensureAgent('vault-probe',1),scope={...record,controllerId:'probe',generation:1};const vault=createVault(db);vault.set(scope.botId,'PROBE','synthetic-vault-canary-7319');
const config={dataDir:root,botsDir:root+'/bots',codexHome:home,codexExecutable:exe,defaultTimezone:'UTC'},agent=new CodexAgent({db,config});const wiki=config.botsDir+'/'+scope.botId;fs.mkdirSync(wiki,{recursive:true});fs.mkdirSync(config.botsDir+'/neighbor',{recursive:true});fs.writeFileSync(config.botsDir+'/neighbor/secret','neighbor');fs.mkdirSync(root+'/private',{recursive:true});fs.writeFileSync(root+'/private/secret','controller');fs.mkdirSync(wiki+'/.temp/other',{recursive:true});fs.writeFileSync(wiki+'/.temp/other/secret','other');
fs.writeFileSync(wiki+'/check.mjs',`import fs from 'node:fs';import {execFileSync} from 'node:child_process';const secret=process.env.PROBE_TOKEN;const inaccessible=${JSON.stringify([config.botsDir+'/neighbor/secret',root+'/private/secret',wiki+'/.temp/other/secret'])}.every(p=>{try{fs.readFileSync(p);return false;}catch{return true;}});const response=execFileSync('curl',['--silent','--show-error','--max-time','15','-o','/dev/null','-w','%{http_code}','https://example.com'],{encoding:'utf8'});console.log(JSON.stringify({secretUsed:secret==='synthetic-vault-canary-7319',inaccessible,httpsStatus:response}));`);
const observations=[];let calls=0;const timer=setTimeout(()=>agent.close(),150000);
try{const s=await agent.session(scope,async(name,args)=>{if(name==='vault_get'){calls++;return vault.get(scope.botId,args.name);}return {error:'not_allowed',description:'Only vault_get is permitted in this probe.'};});s.rpc.on('notification',m=>{if(m.method==='item/completed' && ['agentMessage','commandExecution'].includes(m.params?.item?.type))observations.push({type:m.params.item.type,text:m.params.item.text,output:m.params.item.aggregatedOutput});});const result=await agent.run(scope,[{eventType:'message',messageId:1,textPlain:'Authorized bounded runtime probe. In ONE JavaScript tool execution, discover vault_get and exec_command by ALL_TOOLS names. Read PROBE via vault_get; normalize string JSON tool result if needed. Do NOT print the secret or vault result. Use exec_command to execute node check.mjs with PROBE_TOKEN set to the returned value, using correct shell quoting. Print ONLY the command output JSON (it contains booleans and status, never the secret). Do not send Telegram messages, generate images, spawn agents, or modify files. Finish afterwards.'}],async(name,args)=>{if(name==='vault_get'){calls++;return vault.get(scope.botId,args.name);}return {error:'not_allowed',description:'Only vault_get allowed'};});await result.settled;assert.equal(calls,1);const command=observations.find(o=>o.type==='commandExecution' && o.output?.includes('secretUsed'));assert.ok(command,'Expected shell probe output');assert.deepEqual(JSON.parse(command.output.trim()),{secretUsed:true,inaccessible:true,httpsStatus:'200'});assert.ok(!JSON.stringify(observations).includes('synthetic-vault-canary-7319'));console.log(JSON.stringify({vaultCalls:calls,observations}));}finally{clearTimeout(timer);await agent.deleteSession(record.agentId,db.agent(scope.botId,1)?.threadId);await agent.close();db.close();}
