// Bounded, synthetic-only live test. CLI: node test/live/websocket-mcp.mjs ROOT CODEX_HOME CODEX_EXE
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {WebSocketServer} from 'ws';
import {openDatabase} from '../../src/storage/database.mjs';import {CodexAgent} from '../../src/codex/threads.mjs';import {createController} from '../../src/controller.mjs';import {createVault} from '../../src/storage/vault.mjs';import {createMcpStore} from '../../src/mcp/store.mjs';
const [root,home,exe]=process.argv.slice(2);if(!root||!home||!exe)throw Error('Supply ROOT CODEX_HOME CODEX_EXE');fs.mkdirSync(root,{recursive:true});
const rpcCalls=[];const mcp=http.createServer(async(req,res)=>{let raw='';for await(const p of req)raw+=p;if(req.method!=='POST'){res.writeHead(405).end();return;}const m=JSON.parse(raw);rpcCalls.push({method:m.method,authenticated:req.headers.authorization==='Bearer synthetic-mcp-918',tool:m.params?.name,args:m.params?.arguments});res.setHeader('Content-Type','application/json');if(m.id===undefined){res.writeHead(202).end();return;}
 const v=req.url.includes('v2')?'v2':'v1';let result={};if(m.method==='initialize')result={protocolVersion:m.params.protocolVersion,capabilities:{tools:{}},serverInfo:{name:'test',version:'1'}};if(m.method==='tools/list')result={tools:[{name:'echo_'+v,description:'Return the supplied marker.',inputSchema:{type:'object',properties:{marker:{type:'string'}},required:['marker']}}]};if(m.method==='tools/call')result={content:[{type:'text',text:JSON.stringify({marker:m.params.arguments.marker,version:v})}]};res.end(JSON.stringify({jsonrpc:'2.0',id:m.id,result}));});await new Promise(r=>mcp.listen(0,'127.0.0.1',r));
const ws=new WebSocketServer({port:0,host:'127.0.0.1'});await new Promise(r=>ws.once('listening',r));const received=[],auth=[],binary=[];ws.on('connection',(s,req)=>{auth.push(new URL(req.url,'http://test').searchParams.get('token')==='synthetic-ws-918');s.on('message',(b,isBinary)=>{if(isBinary)binary.push(b.length);else received.push(b.toString());});setTimeout(()=>{if(s.readyState===1){s.send('probe');s.send(Buffer.from([7,8,9]));}},1200);});
const db=openDatabase(root+'/db.sqlite');db.registerBot({botId:'live',telegramId:1,username:'test',ownerId:1});db.saveChat('live',{id:1,type:'private'});const record=db.ensureAgent('live',1);createVault(db).set('live','WS_TEST','synthetic-ws-918');const config={dataDir:root,botsDir:root+'/bots',codexHome:home,codexExecutable:exe,defaultTimezone:'UTC'};
createMcpStore(db).set('live','test',{url:`http://127.0.0.1:${mcp.address().port}/v1`,http_headers:{Authorization:'Bearer synthetic-mcp-918'}});
const agent=new CodexAgent({db,config}),errors=[],outputs=[];let mid=100;const telegram={call:async(b,m,p)=>{if(m==='getMe')return {id:1,username:'test',first_name:'Probe'};if(m==='getMyDescription'||m==='getMyShortDescription')return {};if(m==='sendMessage'){outputs.push(p.text);return {message_id:mid++,date:1,chat:{id:1,type:'private'},text:p.text};}return {};}};
const controller=createController({db,config,agent,telegram,onError:e=>errors.push(e.code??e.message)});
const message=async(text,id,entities=[])=>controller.receive('live',{message:{message_id:id,date:1,chat:{id:1,type:'private'},from:{id:1},text,entities}});
const timer=setTimeout(()=>{controller.close();},240000);
try{
 await message(`Authorized bounded integration probe. Remember marker MEMORY_CANARY_731 for later. No images, subagents, browser or shell. Discover native MCP echo_v1 and invoke it with marker MEMORY_CANARY_731. In JavaScript, read WS_TEST via vault_get (normalize JSON result), construct ws://127.0.0.1:${ws.address().port}?token= plus encodeURIComponent(value), then call ws_open with description 'integration'. Never print URL/token. On subsequent websocket_ready events call ws_pull and send text 'ack' via ws_send once; if binary is present send its path back using ws_send. Do nothing on closed/deleted events. Finish the turn and allow queued notifications to wake you.`,1);
 await controller.idle();await new Promise(r=>setTimeout(r,1800));await controller.idle();
 assert.equal(errors.length,0,JSON.stringify(errors));assert.ok(auth.includes(true));assert.ok(received.includes('ack'));assert.ok(binary.includes(3));assert.ok(rpcCalls.some(c=>c.method==='tools/call'&&c.tool==='echo_v1'&&c.authenticated));
 const thread=db.agent('live',1).threadId;const cfg=`url = "http://127.0.0.1:${mcp.address().port}/v2"\n[http_headers]\nAuthorization = "Bearer synthetic-mcp-918"`;const command='/mcp set test '+cfg;
 await message(command,2,[{type:'pre',offset:14,length:cfg.length}]);await controller.idle();assert.equal(db.agent('live',1).threadId,thread);
 await message('Continue integration probe. Invoke native echo_v2 with the marker you remembered from the earlier turn (do not invent a new marker). Use ws_list to find the existing connection and ws_send text after-refresh. Do not open a new connection. Also report whether native image generation tools are available, without invoking them.',3);await controller.idle();
 assert.equal(auth.length,1);assert.ok(received.includes('after-refresh'));assert.ok(rpcCalls.some(c=>c.tool==='echo_v2'&&c.args.marker==='MEMORY_CANARY_731'));
 const testResult=await agent.testMcp('live',createMcpStore(db).get('live','test'));assert.ok(testResult.tools.includes('echo_v2'));
 const scope=controller.lifecycle.scope({botId:'live',chatId:1,agentId:record.agentId});const connectionId=controller.websockets.list(scope).connections[0].connectionId;
 await message('/ws close '+connectionId,4);await controller.idle();assert.equal(controller.websockets.list(scope).connections[0].status,'closed');
 await message('/ws delete '+connectionId,5);await controller.idle();assert.equal(controller.websockets.list(scope).connections.length,0);
 assert.ok(!JSON.stringify(outputs).includes('synthetic-ws-918'));assert.ok(!JSON.stringify(outputs).includes('synthetic-mcp-918'));
 const report={passed:true,threadPreserved:true,authenticated:auth,received,binary,mcpToolsCalled:rpcCalls.filter(c=>c.method==='tools/call').map(c=>c.tool),testResult,errors,outputs};fs.writeFileSync(root+'/results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{clearTimeout(timer);controller.close();await controller.idle();await agent.deleteSession(record.agentId,db.agent('live',1)?.threadId).catch(()=>{});await agent.close();createVault(db).delete('live','WS_TEST');db.close();for(const s of ws.clients)s.terminate();await new Promise(r=>ws.close(r));await new Promise(r=>mcp.close(r));}
