import {parseMcpConfig,redactMcpConfig} from '../mcp/config.mjs';import {createMcpStore} from '../mcp/store.mjs';import {syntaxError} from './arguments.mjs';
const connectionStatus=result=>result.authStatus==='notLoggedIn'?'authorization required':'connected';
export async function handleMcpCommand({botId,parsed,send,db,requestMcpRefresh,testMcp,mcpOAuth,message,locked=false}){
 if(!locked&&mcpOAuth?.withConnection&&['set','delete','auth','logout'].includes(parsed[0]?.value)){
  const action=parsed[0].value,valid=action==='set'?parsed.length===3&&parsed[2].type==='pre':parsed.length===2;
  if(valid){if(action==='set')parseMcpConfig(parsed[2].value);createMcpStore(db).get(botId,parsed[1].value);await mcpOAuth.cancel(botId,parsed[1].value);}
  return mcpOAuth.withConnection(botId,parsed[1]?.value,()=>handleMcpCommand({botId,parsed,send,db,requestMcpRefresh,testMcp,mcpOAuth,message,locked:true}));
 }
 if(locked&&!['admin','owner'].includes(db.role(botId,message.from.id)))throw syntaxError('Admin role required.');
 const store=createMcpStore(db),parts=parsed.map(x=>x.value),action=parts[0]??'list';
 if(action==='list'&&parts.length<=1){const entries=store.list(botId),rows=[];for(let i=0;i<entries.length;i+=4){rows.push(...await Promise.all(entries.slice(i,i+4).map(async e=>{let status='disabled';if(e.config.enabled!==false){try{if(!testMcp)throw Error();status=connectionStatus(await testMcp(botId,e));}catch(error){status=error.code==='mcp_auth_required'?'authorization required':'unavailable';}}return {name:e.name,prefix:`${e.name} · ${new URL(e.config.url).origin} · `,status};})));}let text='';const entities=[];for(const row of rows){if(text)text+='\n';entities.push({type:'code',offset:text.length,length:row.name.length});text+=row.prefix;entities.push({type:'italic',offset:text.length,length:row.status.length});text+=row.status;}await send({text:text||'No connections',entities});return;}
 if(action==='set'&&parts.length===3&&parsed[2].type==='pre'){
  const config=parseMcpConfig(parts[2]),old=store.get(botId,parts[1]);if(old&&mcpOAuth)await mcpOAuth.logout(botId,old,{refresh:false});store.set(botId,parts[1],config);requestMcpRefresh?.(botId);await send('Configuration saved. Active agents will apply it after their current work.');return;
 }
 if(action==='delete'&&parts.length===2){const old=store.get(botId,parts[1]);if(old&&mcpOAuth)await mcpOAuth.logout(botId,old,{refresh:false});const found=store.delete(botId,parts[1]);if(found)requestMcpRefresh?.(botId);await send(found?'Connection deleted':'Connection not found');return;}
 if(['auth','logout'].includes(action)&&parts.length===2){const entry=store.get(botId,parts[1]);if(!entry)throw syntaxError('MCP connection not found.');if(!mcpOAuth)throw syntaxError('OAuth runtime is not configured.');if(action==='logout'){await mcpOAuth.logout(botId,entry);await send('Local OAuth credentials removed. Active agents will reload after their current work.');}else{const result=await mcpOAuth.start({botId,name:entry.name,userId:message.from.id,chatId:message.chat.id,messageId:message.message_id},entry);try{await send({text:`Open this link and authorize the account:\n${result.url}\n${result.redirectUri ? "\nRedirect URI (register this exact address if required):\n"+result.redirectUri+"\n" : ""}\nAfter authorization, copy the complete URL from the browser address bar, even if the page cannot load. Send it as a reply to your own /mcp auth ${entry.name} command within 10 minutes.`,entities:[],link_preview_options:{is_disabled:true}});}catch(e){await mcpOAuth.cancel(botId,entry.name);throw e;}}return;}
 if(['show','test'].includes(action)&&parts.length===2){const entry=store.get(botId,parts[1]);if(!entry)throw syntaxError('MCP connection not found.');if(action==='show')await send({text:JSON.stringify(redactMcpConfig(entry.config),null,2),entities:[]});else {if(!testMcp)throw syntaxError('MCP runtime is not configured.');const result=await testMcp(botId,entry);await send({text:`${connectionStatus(result)}${result.authStatus?'\nOAuth: '+result.authStatus:''}\nTools: ${result.tools.length}\n${result.tools.join('\n')}`,entities:[]});}return;}
 throw syntaxError('Use /mcp set NAME followed by one pre block of JSON or TOML, or list/show/test/delete/auth/logout.');
}
