CREATE TABLE IF NOT EXISTS tasks (
 taskId TEXT PRIMARY KEY, agentId TEXT NOT NULL REFERENCES agents ON DELETE CASCADE,
 description TEXT NOT NULL, text TEXT NOT NULL, at TEXT, cron TEXT, timezone TEXT,
 createdAt INTEGER NOT NULL, notified INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS task_firings (
 taskId TEXT REFERENCES tasks ON DELETE CASCADE, state TEXT CHECK(state IN ('pending','processing')),
 firstAt INTEGER NOT NULL, lastAt INTEGER NOT NULL, count INTEGER NOT NULL,
 failed INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(taskId,state)
);
CREATE TABLE IF NOT EXISTS generated_images (
 path TEXT PRIMARY KEY, botId TEXT NOT NULL REFERENCES bots ON DELETE CASCADE, agentId TEXT NOT NULL, threadId TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS git_settings(botId TEXT PRIMARY KEY REFERENCES bots ON DELETE CASCADE, branch TEXT NOT NULL, remoteUrl TEXT NOT NULL, secretRef TEXT);
INSERT OR IGNORE INTO schema_migrations VALUES(4);
