import test from 'node:test';
import assert from 'node:assert/strict';
import {openDatabase} from '../../src/storage/database.mjs';
import {createController} from '../../src/controller.mjs';
test('stop discards collected albums and disabled album parts cannot trigger after start',async t=>{
 const db=openDatabase(':memory:');db.registerBot({botId:'b',telegramId:42,username:'bot',ownerId:1});db.saveChat('b',{id:-1,type:'group'});db.ensureAgent('b',-1);const runs=[];const c=createController({db,agent:{run:async(s,e)=>runs.push(e),deleteSession:async()=>{}},telegram:{call:async()=>({})}});t.after(async()=>{c.close();await c.idle();db.close();});const send=(id,text,extra={})=>c.receive('b',{message:{message_id:id,date:1,chat:{id:-1,type:'group'},from:{id:1},text,...extra}});await send(1,'@bot',{media_group_id:'album',entities:[{type:'mention',offset:0,length:4}]});await send(2,'/agent stop');await c.idle();await send(3,'@bot',{media_group_id:'disabled',entities:[{type:'mention',offset:0,length:4}]});await send(4,'/agent start');await new Promise(r=>setTimeout(r,1100));await c.idle();assert.equal(runs.length,0);assert.ok(db.getMessage('b',-1,1));assert.ok(db.getMessage('b',-1,3));
});
test('passive supergroup records history; manager starts and stops without losing notes or tasks',async t=>{
 const db=openDatabase(':memory:');db.registerBot({botId:'b',telegramId:42,username:'bot',ownerId:1});db.setRole('b',2,'manager');db.saveChat('b',{id:-1,type:'supergroup',title:'Friends'});
 const runs=[],replies=[];const c=createController({db,agent:{run:async(s,e)=>runs.push(e),deleteSession:async()=>{}},telegram:{call:async(b,m,a)=>{if(m==='sendMessage')replies.push(a.text);return{};}}});t.after(async()=>{c.close();await c.idle();db.close();});
 const send=(id,text)=>c.receive('b',{message:{message_id:id,date:1,chat:{id:-1,type:'supergroup'},from:{id:2},text,entities:text.startsWith('@')?[{type:'mention',offset:0,length:4}]:[]}});
 await send(1,'@bot hello');await c.idle();assert.equal(runs.length,0);assert.ok(db.getMessage('b',-1,1));
 await send(2,'/agent start');await send(3,'@bot hello');await c.idle();assert.equal(runs.length,1);
 const a=db.agent('b',-1);db.sql.prepare('UPDATE agents SET notes=? WHERE agentId=?').run('remember',a.agentId);const task=c.scheduler.schedule(a,{description:'test',text:'do',at:'2099-01-01T00:00:00Z'});
 await send(4,'/agent stop');await c.idle();assert.equal(db.agent('b',-1).notes,'remember');assert.ok(c.scheduler.task(task.taskId));await send(5,'@bot ignored');await c.idle();assert.equal(runs.length,1);
 c.scheduler.fire(task.taskId,Date.now());await c.idle();assert.equal(runs.length,1);await send(6,'/agent start');await c.idle();assert.equal(runs.length,2);assert.equal(runs[1][0].missedReason,'agent_disabled');
});
test('stop waits for root and child, keeps history, and blocks start until settled',async t=>{
 const db=openDatabase(':memory:');db.registerBot({botId:'b',telegramId:42,username:'bot',ownerId:1});db.saveChat('b',{id:1,type:'private'});const a=db.ensureAgent('b',1);let rootDone,childDone;const root=new Promise(r=>rootDone=r),child=new Promise(r=>childDone=r),runs=[],deleted=[],replies=[];
 const c=createController({db,agent:{run:async(s,e)=>{runs.push(e);await root;return{settled:child};},deleteSession:async()=>deleted.push('deleted')},telegram:{call:async(b,m,a)=>{if(m==='sendMessage')replies.push(a.text);return{};}}});t.after(async()=>{rootDone();childDone();c.close();await c.idle();db.close();});
 const send=(id,text)=>c.receive('b',{message:{message_id:id,date:1,chat:{id:1,type:'private'},from:{id:1},text}});await send(1,'work');await new Promise(r=>setImmediate(r));await send(2,'queued');await send(3,'/agent stop');await send(4,'/agent start');assert.match(replies.at(-1),/stopping/);await send(5,'history only');assert.ok(db.getMessage('b',1,5));await c.receive('b',{edited_message:{message_id:1,date:1,edit_date:2,chat:{id:1,type:'private'},from:{id:1},text:'edited after stop'}});assert.equal(c.queue.state(a.agentId).events.length,0);assert.equal(deleted.length,0);rootDone();await new Promise(r=>setImmediate(r));assert.equal(deleted.length,0);childDone();await c.idle();assert.equal(deleted.length,1);assert.equal(runs.length,1);assert.equal(db.agent('b',1).stopPending,0);assert.equal(db.getChat('b',1).agentEnabled,0);
});
test('failed stop cleanup is recoverable by clear without enabling the agent',async t=>{
 const db=openDatabase(':memory:');db.registerBot({botId:'b',telegramId:42,username:'bot',ownerId:1});db.saveChat('b',{id:1,type:'private'});db.ensureAgent('b',1);let fail=true;const c=createController({db,agent:{run:async()=>{},deleteSession:async()=>{if(fail)throw new Error('temporary');}},telegram:{call:async()=>({})}});t.after(async()=>{c.close();await c.idle();db.close();});const send=text=>c.receive('b',{message:{message_id:1,chat:{id:1,type:'private'},from:{id:1},text}});await send('/agent stop');await c.idle();assert.equal(db.agent('b',1).stopPending,1);fail=false;await send('/agent clear');await c.idle();assert.equal(db.agent('b',1).stopPending,0);assert.equal(db.getChat('b',1).agentEnabled,0);await send('/agent start');assert.equal(db.getChat('b',1).agentEnabled,1);
});
test('cron firing during processing retains disabled reason through failed completion',async t=>{
 const db=openDatabase(':memory:');db.registerBot({botId:'b',telegramId:42,username:'bot',ownerId:1});db.saveChat('b',{id:1,type:'private'});const a=db.ensureAgent('b',1);const {Scheduler}=await import('../../src/scheduler/tasks.mjs');const s=new Scheduler({db,timers:false,enqueue:()=>{}});const task=s.schedule(a,{description:'check',text:'check',cron:'* * * * *',timezone:'UTC'});s.fire(task.taskId,1000);s.take(task.taskId);db.sql.prepare('UPDATE chats SET agentEnabled=0').run();s.fire(task.taskId,2000);s.complete(task.taskId,false);const pending=db.sql.prepare("SELECT * FROM task_firings WHERE taskId=? AND state='pending'").get(task.taskId);assert.equal(pending.missedReason,'agent_disabled');assert.equal(pending.count,2);s.close();db.close();
});
test('restart completes a durable stop without starting the old context',async t=>{
 const db=openDatabase(':memory:');db.registerBot({botId:'b',telegramId:42,username:'bot',ownerId:1});db.saveChat('b',{id:1,type:'private'});const a=db.ensureAgent('b',1);db.sql.prepare('UPDATE chats SET agentEnabled=0').run();db.sql.prepare('UPDATE agents SET stopPending=1,contextResetPending=1,threadId=?').run('old');let deleted=0,runs=0;const c=createController({db,agent:{run:async()=>runs++,deleteSession:async()=>deleted++},telegram:{call:async()=>({})}});await c.idle();assert.equal(deleted,1);assert.equal(runs,0);assert.equal(db.agent('b',1).stopPending,0);c.close();await c.idle();db.close();
});
