import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { openDatabase } from '../../src/storage/database.mjs';
import { createController } from '../../src/controller.mjs';
test('group trigger starts two-minute ten-message window; passive chat has no agent', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'tg-groups-')); const db = openDatabase(path.join(root, 'db.sqlite'));
  const batches = []; let time = 1000;
  const c = createController({ db, telegram: { call: async () => ({}) }, agent: { run: async (_, events) => batches.push(events) }, clock: () => time });
  t.after(() => { c.close(); db.close(); fs.rmSync(root, { recursive: true, force: true }); });
  db.registerBot({ botId: 'b1', telegramId: 42, username: 'test_bot', ownerId: 1 });
  db.saveChat('b1', { id: -1, type: 'group', title: 'Group' }); db.saveChat('b1', { id: -2, type: 'supergroup', title: 'Passive' });
  const send = async (id, text, chatId = -1, extra = {}) => { await c.receive('b1', { update_id: id, message: { message_id: id, date: 1791383000, chat: { id: chatId, type: chatId === -1 ? 'group' : 'supergroup' }, from: { id: 5, first_name: 'X' }, text, ...extra } }); await c.idle(); };
  await send(1, 'hello'); assert.equal(batches.length, 0);
  await send(2, '@test_bot hello', -1, { entities: [{ type: 'mention', offset: 0, length: 9 }] });
  for (let i = 3; i <= 13; i++) await send(i, 'follow-up');
  assert.equal(batches.length, 11); // trigger + ten ordinary events
  await send(14, 'publication', -2); assert.equal(db.agent('b1', -2), null); assert(db.getMessage('b1', -2, 14));
  await send(16, '/hello', -2); assert(db.getMessage('b1', -2, 16));
  time += 120001; await send(15, 'late'); assert.equal(batches.length, 11);
});
test('removal from a group stops the session and fences its tools without leaving again', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'tg-removed-')), db = openDatabase(path.join(root, 'db.sqlite'));
  db.registerBot({ botId: 'b', telegramId: 42, username: 'test', ownerId: 1 }); db.saveChat('b', { id: -1, type: 'group' });
  let oldScope; const stopped = [], telegramCalls = [];
  const c = createController({ db, telegram: { call: async (_bot, method) => { telegramCalls.push(method); return {}; } }, agent: { run: async scope => { oldScope = scope; }, deleteSession: async id => stopped.push(id) } });
  t.after(() => { c.close(); db.close(); fs.rmSync(root, { recursive: true, force: true }); });
  await c.receive('b', { message: { message_id: 1, date: 1791383000, chat: { id: -1, type: 'group' }, from: { id: 1 }, text: '@test', entities: [{ type: 'mention', offset: 0, length: 5 }] } }); await c.idle();
  await c.receive('b', { my_chat_member: { chat: { id: -1, type: 'group' }, from: { id: 1 }, new_chat_member: { status: 'left' } } });
  assert.deepEqual(stopped, [oldScope.agentId]);
  await assert.rejects(c.invoke(oldScope, 'time', {}), { code: 'connection_expired' });
  assert.equal(db.getChat('b', -1), null); assert.ok(!telegramCalls.includes('leaveChat'));
});
test('album delivery uses the latest saved caption when edited before collection completes', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'tg-album-edit-')), db = openDatabase(path.join(root, 'db.sqlite'));
  db.registerBot({ botId: 'b', telegramId: 42, username: 'test', ownerId: 1 }); db.saveChat('b', { id: -1, type: 'group' });
  let finish; const busy = new Promise(resolve => { finish = resolve; });
  const c = createController({ db, telegram: { call: async () => ({}) }, agent: { run: async () => busy } });
  t.after(async () => { finish(); c.close(); await c.idle(); db.close(); fs.rmSync(root, { recursive: true, force: true }); });
  const chat = { id: -1, type: 'group' }, from = { id: 1 };
  await c.receive('b', { message: { message_id: 1, date: 1791383000, chat, from, text: '@test', entities: [{ type: 'mention', offset: 0, length: 5 }] } });
  await new Promise(resolve => setImmediate(resolve));
  const photo = { message_id: 2, date: 1791383000, chat, from, caption: 'old', media_group_id: 'album', photo: [{ file_id: 'id', width: 100, height: 100 }] };
  await c.receive('b', { message: photo });
  await c.receive('b', { edited_message: { ...photo, caption: 'new', edit_date: 1791383001 } });
  await new Promise(resolve => setTimeout(resolve, 1100));
  const a = db.agent('b', -1), event = c.queue.state(a.agentId).events[0].event;
  assert.equal((Array.isArray(event) ? event[0] : event).captionPlain, 'new');
  finish(); await c.idle();
});
test('group migration leaves the new supergroup ID and deletes old group data', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'tg-migrate-')), db = openDatabase(path.join(root, 'db.sqlite'));
  db.registerBot({ botId: 'b', telegramId: 42, username: 'test', ownerId: 1 }); db.saveChat('b', { id: -1, type: 'group' }); db.ensureAgent('b', -1);
  const leaves = [], c = createController({ db, telegram: { call: async (_bot, method, args) => { if (method === 'leaveChat') leaves.push(args.chat_id); return {}; } }, agent: { run: async () => {} } });
  t.after(() => { c.close(); db.close(); fs.rmSync(root, { recursive: true, force: true }); });
  await c.receive('b', { message: { message_id: 5, date: 1791383000, chat: { id: -1, type: 'group' }, migrate_to_chat_id: -1001 } });
  assert.deepEqual(leaves, [-1001]); assert.equal(db.getChat('b', -1), null);
});
test('ordinary loud events expire while queued; direct triggers remain eligible', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'tg-loud-expire-')), db = openDatabase(path.join(root, 'db.sqlite'));
  db.registerBot({ botId: 'b', telegramId: 42, username: 'test', ownerId: 1 }); db.saveChat('b', { id: -1, type: 'group' });
  let now = 1000, finish; const busy = new Promise(resolve => { finish = resolve; }), batches = [];
  const c = createController({ db, clock: () => now, telegram: { call: async () => ({}) }, agent: { run: async (_scope, events) => { batches.push(events); if (batches.length === 1) await busy; } } });
  t.after(async () => { finish(); c.close(); await c.idle(); db.close(); fs.rmSync(root, { recursive: true, force: true }); });
  const send = (id, trigger) => c.receive('b', { message: { message_id: id, date: 1791383000, chat: { id: -1, type: 'group' }, from: { id: 1 }, text: trigger ? '@test' : 'follow-up', ...(trigger ? { entities: [{ type: 'mention', offset: 0, length: 5 }] } : {}) } });
  await send(1, true); await new Promise(resolve => setImmediate(resolve)); await send(2, false);
  now += 120001; finish(); await c.idle(); assert.equal(batches.length, 1); assert.ok(db.getMessage('b', -1, 2));
  await send(3, true); await c.idle(); assert.equal(batches.length, 2); assert.equal(batches[1][0].historyGap, true);
});
