import test from 'node:test';import assert from 'node:assert/strict';
import {openDatabase} from '../../src/storage/database.mjs';import {createCommands} from '../../src/commands/router.mjs';import {createMcpStore} from '../../src/mcp/store.mjs';
import {createController} from '../../src/controller.mjs';
function fixture(t){const db=openDatabase(':memory:');t.after(()=>db.close());db.registerBot({botId:'b',telegramId:42,username:'bot',ownerId:1});db.setRole('b',2,'admin');db.setRole('b',3,'user');createMcpStore(db).set('b','cal',{url:'https://mcp.test'});const calls=[],auth=[];const oauth={start:async(...x)=>{auth.push(['start',...x]);return {url:'https://issuer.test/auth?state=test'};},finish:async(...x)=>auth.push(['finish',...x]),logout:async(...x)=>auth.push(['logout',...x]),cancel:async()=>{}};const router=createCommands({db,mcpOAuth:oauth,telegram:{call:async(b,m,p)=>{calls.push({m,...p});return {};}}});const send=(text,extra={})=>router.handle('b',{text,message_id:11,from:{id:1},chat:{id:1,type:'private'},...extra});const invitation={text:'/mcp auth cal',message_id:10,from:{id:1},chat:{id:1,type:'private'}};return {db,calls,auth,send,invitation};}
test('MCP auth is admin-only, private, replies with a non-previewed authorization link',async t=>{const f=fixture(t);await f.send('/mcp auth cal');assert.equal(f.auth[0][0],'start');assert.equal(f.calls[0].reply_parameters.message_id,11);assert.equal(f.calls[0].link_preview_options.is_disabled,true);await f.send('/mcp auth cal',{from:{id:3}});await f.send('/mcp auth cal',{chat:{id:-1,type:'group'}});assert.equal(f.auth.length,1);});
test('callback reply uses the original command identity and never leaks callback in responses',async t=>{const f=fixture(t);const url='http://127.0.0.1:1234/callback?code=secret-code&state=test';assert.equal(await f.send(url,{reply_to_message:f.invitation}),true);assert.equal(f.auth[0][0],'finish');assert.equal(f.auth[0][1].messageId,10);assert.equal(f.auth[0][2],url);assert.equal(f.calls.at(-1).m,'deleteMessage');assert.ok(!JSON.stringify(f.calls).includes('secret-code'));});
test('callback rejects чужие/edited invitations, revoked access and formatting, always deletes the URL',async t=>{const f=fixture(t);for(const change of [{from:{id:2}},{edit_date:1},{chat:{id:2,type:'private'}},{sender_chat:{id:1}},{text:'/mcp auth@other cal'}]){await f.send('http://localhost/?code=secret',{reply_to_message:{...f.invitation,...change}});assert.equal(f.calls.at(-1).m,'deleteMessage');}await f.send('http://localhost/?code=secret',{from:{id:3},reply_to_message:f.invitation});assert.equal(f.calls.at(-1).m,'deleteMessage');assert.equal(f.auth.length,0);});
test('logout delegates and settings replacement/deletion clears local OAuth credentials',async t=>{const f=fixture(t);await f.send('/mcp logout cal');assert.equal(f.auth[0][0],'logout');await f.send('/mcp delete cal');assert.equal(f.auth[1][0],'logout');assert.equal(createMcpStore(f.db).get('b','cal'),null);});
test('OAuth replies reject pre/bold text but accept a URL entity, code or spoiler',async t=>{const f=fixture(t),url='http://127.0.0.1/?code=secret&state=x';for(const type of ['pre','bold'])await f.send(url,{reply_to_message:f.invitation,entities:[{type,offset:0,length:url.length}]});assert.equal(f.auth.length,0);for(const type of ['url','code','spoiler'])await f.send(url,{reply_to_message:f.invitation,entities:[{type,offset:0,length:url.length}]});assert.equal(f.auth.length,3);});
test('credential cleanup failure keeps the old MCP configuration',async t=>{const f=fixture(t);const calls=[];const router=createCommands({db:f.db,mcpOAuth:{logout:async()=>{throw Object.assign(Error('Cleanup failed'),{safe:true});}},telegram:{call:async(b,m,p)=>calls.push({m,...p})}});await router.handle('b',{text:'/mcp delete cal',message_id:12,from:{id:1},chat:{id:1,type:'private'}});assert.ok(createMcpStore(f.db).get('b','cal'));assert.match(calls[0].text,/Cleanup failed/);});
test('edited, unquoted and changed-invitation callbacks never enter controller history or model input',async t=>{const f=fixture(t),runs=[],controller=createController({db:f.db,agent:{run:async(s,e)=>runs.push(e)},telegram:{call:async(b,m,p)=>f.calls.push({m,...p})}});t.after(async()=>{controller.close();await controller.idle();});const callback='http://127.0.0.1/callback?code=sensitive&state=test';
 for(const [id,edited,quote] of [[21,true,f.invitation],[22,false,{...f.invitation,text:'changed',edit_date:1}],[23,false,undefined]]){const m={message_id:id,date:1,text:callback,from:{id:1},chat:{id:1,type:'private'},...(quote?{reply_to_message:quote}:{}),...(edited?{edit_date:2}:{})};await controller.receive('b',{[edited?'edited_message':'message']:m});assert.equal(f.db.getMessage('b',1,id),null);assert.equal(f.calls.at(-1).m,'deleteMessage');}
 await controller.idle();assert.deepEqual(runs,[]);assert.ok(!JSON.stringify(f.calls).includes('sensitive'));
});
