import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { openDatabase } from '../../src/storage/database.mjs';
import { Scheduler } from '../../src/scheduler/tasks.mjs';
import { createController } from '../../src/controller.mjs';
test('background children hold scheduler completion without blocking new chat turns', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'tg-scheduler-child-')), db = openDatabase(path.join(root, 'db.sqlite'));
  db.registerBot({ botId: 'b', telegramId: 42, username: 'test', ownerId: 1 });
  let finish; const settled = new Promise(resolve => { finish = resolve; }), runs = [];
  const c = createController({ db, telegram: { call: async () => ({}) }, agent: { run: async (_scope, events) => { runs.push(events); if (events.some(e => e.eventType === 'scheduled')) return { settled }; } } });
  t.after(() => { finish(); c.close(); db.close(); fs.rmSync(root, { recursive: true, force: true }); });
  const message = id => ({ message: { message_id: id, date: 1791383000, chat: { id: 1, type: 'private' }, from: { id: 1 }, text: 'hello' } });
  await c.receive('b', message(1)); await c.idle(); c.scheduler.timers = false;
  const a = db.agent('b', 1), { taskId } = c.scheduler.schedule(a, { at: '2027-01-01T00:00:00Z', description: 'test', text: 'work' });
  c.scheduler.fire(taskId, Date.now()); await new Promise(resolve => setImmediate(resolve));
  assert.equal(c.queue.state(a.agentId).busy, false);
  assert.equal(db.sql.prepare('SELECT state FROM task_firings WHERE taskId=?').get(taskId)?.state, 'processing');
  await c.receive('b', message(2)); await new Promise(resolve => setImmediate(resolve));
  assert.equal(runs.length, 3); assert.ok(c.scheduler.task(taskId));
  finish(); await c.idle(); assert.equal(c.scheduler.task(taskId), undefined);
});
test('pending cron coalesces, processing waits, restart does not add downtime', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'tg-scheduler-')); const db = openDatabase(path.join(root, 'db.sqlite'));
  db.registerBot({ botId: 'b1', telegramId: 42, username: 'test', ownerId: 1 }); db.saveChat('b1', { id: 1, type: 'private' }); const a = db.ensureAgent('b1', 1);
  const queued = []; const s = new Scheduler({ db, enqueue: (agentId, e) => queued.push(e), clock: () => Date.parse('2026-10-07T10:00:00Z'), timers: false });
  t.after(() => { s.close(); db.close(); fs.rmSync(root, { recursive: true, force: true }); });
  const { taskId } = s.schedule(a, { cron: '* * * * *', timezone: 'UTC', description: 'test', text: 'work' });
  for (let i = 0; i < 4; i++) s.fire(taskId, Date.parse('2026-10-07T10:00:00Z') + i * 60000);
  assert.equal(queued.length, 1); const e = s.take(taskId); assert.equal(e.occurrences, 4);
  s.fire(taskId, Date.parse('2026-10-07T10:04:00Z')); assert.equal(queued.length, 1);
  s.complete(taskId, true); assert.equal(queued.length, 2);
  s.recover(); assert.equal(s.take(taskId).scheduledAt, '2026-10-07T10:04:00.000Z');
});
test('discarded RAM queue releases scheduler marker and keeps the missed action retryable', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'tg-scheduler-failure-')), db = openDatabase(path.join(root, 'db.sqlite'));
  db.registerBot({ botId: 'b', telegramId: 42, username: 'bot', ownerId: 1 }); db.saveChat('b', { id: 1, type: 'private' });
  const a = db.ensureAgent('b', 1), events = [], notifications = [];
  const s = new Scheduler({ db, timers: false, enqueue: (_id, event) => events.push(event), notify: task => notifications.push(task.taskId) });
  t.after(() => { s.close(); db.close(); fs.rmSync(root, { recursive: true, force: true }); });
  const { taskId } = s.schedule(a, { at: '2027-01-01T00:00:00Z', description: 'later', text: 'do work' });
  s.fire(taskId, 1000); assert.equal(s.queued.has(taskId), true);
  s.failQueued(a.agentId);
  assert.equal(s.queued.has(taskId), false);
  assert.equal(db.sql.prepare('SELECT failed FROM task_firings WHERE taskId=?').get(taskId).failed, 1);
  assert.deepEqual(notifications, [taskId]);
  s.retry(taskId); assert.equal(events.length, 2);
  assert.throws(() => s.retry(taskId), /being processed/);
  assert.equal(s.take(taskId).retry, true);
  s.complete(taskId, false);
  s.offer(taskId);
  s.failQueued(a.agentId); assert.deepEqual(notifications, [taskId]);
});
