import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {WebSocketServer} from 'ws';
import {openDatabase} from '../../src/storage/database.mjs';import {createController} from '../../src/controller.mjs';
test('controller WS triggers idle agent, admin permissions, delete cancels ready',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'ws-controller-')),db=openDatabase(':memory:');db.registerBot({botId:'b',telegramId:1,username:'bot',ownerId:1});db.saveChat('b',{id:1,type:'private'});const a=db.ensureAgent('b',1);db.setRole('b',2,'user');const runs=[],calls=[],agent={run:async(s,e)=>{runs.push(e);}};
 const c=createController({db,config:{botsDir:root},agent,telegram:{call:async(b,m,p)=>{calls.push({m,p});return {};}}});t.after(async()=>{c.close();await c.idle();db.close();fs.rmSync(root,{recursive:true,force:true});});const server=new WebSocketServer({port:0});await new Promise(r=>server.once('listening',r));t.after(()=>server.close());let peer;server.on('connection',ws=>peer=ws);
 const scope=c.lifecycle.scope({botId:'b',chatId:1,agentId:a.agentId});const {connectionId}=await c.invoke(scope,'ws_open',{url:`ws://127.0.0.1:${server.address().port}?token=hidden`,description:'test'});peer.send('data');await new Promise(r=>setTimeout(r,30));await c.idle();assert.equal(runs[0][0].eventType,'websocket_ready');assert.ok(!JSON.stringify(runs).includes('data'));
 const cmd=async(text,id=1)=>{await c.receive('b',{message:{message_id:10,chat:{id:1,type:'private'},from:{id},text}});await c.idle();};await cmd('/ws list');assert.match(calls.at(-1).p.text,/test/);assert.ok(!JSON.stringify(calls).includes('hidden'));await cmd('/ws close '+connectionId,2);assert.equal(c.websockets.list(scope).connections[0].status,'open');await cmd('/ws close '+connectionId);assert.ok(runs.flat().some(e=>e.reason==='admin'));await cmd('/ws delete '+connectionId);assert.equal(c.websockets.list(scope).connections.length,0);
});
test('restart discards old WS binary directories but preserves other temp files',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'ws-restart-')),db=openDatabase(':memory:');db.registerBot({botId:'b',telegramId:1,username:'bot',ownerId:1});db.saveChat('b',{id:1,type:'private'});const a=db.ensureAgent('b',1),dir=path.join(root,'b','.temp',a.agentId);fs.mkdirSync(path.join(dir,'websocket','old'),{recursive:true});fs.writeFileSync(path.join(dir,'websocket','old','packet.bin'),'old');fs.writeFileSync(path.join(dir,'keep.txt'),'keep');
 const c=createController({db,config:{botsDir:root},agent:{},telegram:{call:async()=>({})}});t.after(async()=>{c.close();await c.idle();db.close();fs.rmSync(root,{recursive:true,force:true});});assert.equal(fs.existsSync(path.join(dir,'websocket')),false);assert.equal(fs.readFileSync(path.join(dir,'keep.txt'),'utf8'),'keep');
});
